sessions_db = [
    {
        "id": 1,
        "route": "Kampus Utama - Stasiun Tugu",
        "driver": "Budi Santoso",
        "capacity": 12,
        "departure_time": "07:00",
        "status": "Available",
    },
    {
        "id": 2,
        "route": "Kampus Utama - Terminal Giwangan",
        "driver": "Siti Aminah",
        "capacity": 10,
        "departure_time": "07:30",
        "status": "Booked",
    },
    {
        "id": 3,
        "route": "Kampus 2 - Malioboro",
        "driver": "Agus Wijaya",
        "capacity": 8,
        "departure_time": "08:00",
        "status": "Available",
    },
    {
        "id": 4,
        "route": "Asrama - Kampus Utama",
        "driver": "Dewi Lestari",
        "capacity": 14,
        "departure_time": "06:45",
        "status": "Full",
    },
    {
        "id": 5,
        "route": "Kampus Utama - Bandara Adisutjipto",
        "driver": "Rudi Hartono",
        "capacity": 6,
        "departure_time": "09:15",
        "status": "Available",
    },
    {
        "id": 6,
        "route": "Kampus 2 - Kampus Utama",
        "driver": "Nurul Hidayah",
        "capacity": 11,
        "departure_time": "10:00",
        "status": "Booked",
    },
    {
        "id": 7,
        "route": "Kampus Utama - Jombor",
        "driver": "Hendra Kusuma",
        "capacity": 9,
        "departure_time": "12:30",
        "status": "Available",
    },
    {
        "id": 8,
        "route": "Kampus Utama - Prawirotaman",
        "driver": "Ratna Sari",
        "capacity": 7,
        "departure_time": "13:15",
        "status": "Maintenance",
    },
    {
        "id": 9,
        "route": "Asrama - Kampus 2",
        "driver": "Joko Prasetyo",
        "capacity": 13,
        "departure_time": "14:00",
        "status": "Available",
    },
    {
        "id": 10,
        "route": "Kampus Utama - Pasar Kraton",
        "driver": "Maya Anggraini",
        "capacity": 10,
        "departure_time": "15:30",
        "status": "Booked",
    },
    {
        "id": 11,
        "route": "Kampus 2 - Terminal Jombor",
        "driver": "Fitri Ramadhani",
        "capacity": 12,
        "departure_time": "16:45",
        "status": "Available",
    },
    {
        "id": 12,
        "route": "Kampus Utama - Seturan",
        "driver": "Bayu Nugroho",
        "capacity": 15,
        "departure_time": "17:30",
        "status": "Full",
    },
    {
        "id": 13,
        "route": "Kampus Utama - Kaliurang",
        "driver": "Lina Marlina",
        "capacity": 8,
        "departure_time": "18:15",
        "status": "Available",
    },
]
